### ISSUE TITLE
[Bug]: Issue using Scribe Provider

### ISSUE THREAD

**Issue by bushvin** [bushvin/actor-export#12]
### Contact Details

murgol

### Foundry VTT version

12.328

### Game system

pf2e

### Game system version

6.0.4

### actor-export module version

2024.7.1

### What browsers are you seeing the problem on?

Chrome

### What Provider is affected?

PF2e Scribe Generator

### What happened?

The probleme : if I try to export a character's ABC, I receive this error in the console : 
```
modules/actor-export/providers/pf2e-scribe/actor-abc:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
foundry.js:71791 actor-export | There was an error updating the export file
fetch @ foundry.js:71791
BaseProvider.js:169 error: TypeError: Cannot read properties of undefined (reading 'map')
    at scribeCharacterFeat.scribify (ScribeProvider.js:313:60)
    at async scribeProvider.updateFile (ScribeProvider.js:1113:31)
    at async BaseProvider.js:166:21
(anonymous) @ BaseProvider.js:169
foundry.js:71791 actor-export | Failed to download file: Failed to update /modules/actor-export/providers/pf2e-scribe/actor-abc: Cannot read properties of undefined (reading 'map')
fetch @ foundry.js:71791
```

### Attachments

[fvtt-Actor-elenion-nerth-vlif8OYuWjOxZDkz.json](https://github.com/user-attachments/files/16338935/fvtt-Actor-elenion-nerth-vlif8OYuWjOxZDkz.json)

**Comment by bushvin** [comment]
Fixed with https://github.com/bushvin/actor-export/commit/7e16ca7d2be46ec0b5bfe21fa626788a39d7a8ac
